#!/usr/bin/env bash
# script that configures a new Ubuntu machine with HAproxy load balancer

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
	bind *:80
	mode http
	default_backend Web_Servers
backend Web_Servers
	balance roundrobin
	mode http
	server web-01 44.201.70.229:80 check
	server web-02 3.239.99.12:80 check
EOF

service haproxy restart